### ISSUE TITLE
HTTP Error : Could not resolve host ' s10.api.mailchimp.com '

### ISSUE THREAD

**Issue by henry-alderslade** [dannyvankooten/mailchimp-for-wordpress#65]
Error when entering api key into plugin.

Appears to be a problem with the length of the API key. 

Fix -

File mailchimp\includes\class-api.php
line 46 - $this->api_url = 'https://' . substr( $api_key, -3 ) . '.api.mailchimp.com/2.0/';

Change -3 to -4

**Comment by iMazed** [comment]
Seeing multiple similar issues appearing withing the WordPress.org support forum (3 open topics so far). Tried recreating on local and live server, but no issues here. Can't confirm fix; applying that fix caused issues where there were none before.

**Comment by henry-alderslade** [comment]
Just out of curiousity could you tell me how many characters your api key has?

**Comment by henry-alderslade** [comment]
It appears this is occuring because the code is assuming the portion after the dash in the API key will be 3 characters long. The problem is that it can now span up to 4 characters, as mine does "us10". So the fix will only work for people that have 4 characters after the dash in the API key.

quote from MailChimp API v2.0 Documentation -

"https://<dc>.api.mailchimp.com/2.0/ - 

<dc> should be replaced with the portion after the dash in your API Key. e.g. "us1", "us2", "uk1", etc"

**Comment by dannyvankooten** [comment]
Hi @henry-alderslade , thanks for opening an issue here. That's a valid bug you got there, consider it fixed. :+1: 

I will push out a plugin update as soon as I can. If you're in a hurry, you can [download the development version of the plugin here](https://github.com/dannyvankooten/mailchimp-for-wordpress/archive/master.zip).

Hope that helps, thanks again!

**Comment by henry-alderslade** [comment]
No problem Danny, glad I could help :+1:
