### ISSUE TITLE
Need to HTML-escape when quotes appear in email placeholder attribute

### ISSUE THREAD

**Issue by davidpelfree** [dannyvankooten/mailchimp-for-wordpress#72]
Hi.

I used quote sign inside email placeholder. In HTML it was rendered as is, and as a result it's an invalid HTML. I got something like: 
```
<input type="email" id="mc4wp_email" name="EMAIL" placeholder="here is an invalid quote sign:". " required />
```
The quote sign should have been replaced with &quot; HTML entity.

**Comment by dannyvankooten** [comment]
Hi David,

If you use the "Add MailChimp field" tool to generate the correct HTML for your fields then the various attributes will be properly encoded.

If you generate your own HTML then the plugin will just take this over as is - parsing and checking the given HTML is an expensive and difficult process..

So, if you write your own HTML for the fields then this is unfortunately not really something the plugin can take care of for you. It does escape attributes automatically when using the Field Helper though!
