### ISSUE TITLE
Comment form: Checkbox should be above not below submit button

### ISSUE THREAD

**Issue by jnachtigall** [dannyvankooten/mailchimp-for-wordpress#82]
The checkbox should be above the "submit" button on the comment form, see this for illustration: 
Here's a live example at https://www.fiveroasters.de/blog/rohkaffee-im-shop/

![2015-02-27 16_43_55-rohkaffee im shop five roasters](https://cloud.githubusercontent.com/assets/3307404/6415579/3983a4c2-bea0-11e4-93e8-8592b918d27f.png)

Should be the way it is for the registration form, see here at the right hand side: https://www.fiveroasters.de/mein-konto/

![2015-02-27 16_45_27-dein konto five roasters](https://cloud.githubusercontent.com/assets/3307404/6415571/313bbe30-bea0-11e4-80b2-2206ec55b815.png)

**Comment by dannyvankooten** [comment]
Hi @jnachtigall ,

Thank you for the detailed report, very helpful! However, unfortunately this isn't really a plugin issue. The plugin hooks into your comment form by using a so called "action hook". The placement of the checkbox depends on whether your theme calls this action hook before or after the submit button.

Please go to your theme folder and look for a file named `comments.php`. Inside, look for a line that looks like this.

```php
do_action( 'comment_form' );
```

Move that line above the HTML for the submit button and you should be good to go. :-)

Hope that helps. If not, let me know!

**Comment by jnachtigall** [comment]
Hi @dannyvankooten,

I’d like to bring this up again, because this is fixed for blog comments where it really was a theming issuee. But for *product reviews* (woocommerce) the problem persists.

See it at https://www.fiveroasters.de/shop/filterkaffee-stellers-jay/ under the “Bewertungen” (reviews) tab: The checkbox “Interessiert an Kaffeekultur? Dann hier Häkchen setzen um unseren zweimonatlichen Newsletter zu erhalten.” should be above the “Senden” button. 

I talked to the theme developer and he said:

> That isn’t due to a theme file. The template for it at least isn’t overridden by the theme, it’s the content-single-reviews.php file in woocommerce. But the thing is woocomerce is only editing the fields and calling the wordpress comment_form() function.
> 
> When you try the mail chimp plugin with any default theme the checkbox also comes after the submit button so if you want to ask someone it would be the mail chimp plugin.
