### ISSUE TITLE
_mc4wp_required_but_not_really field is not hidden

### ISSUE THREAD

**Issue by fuzaylov** [dannyvankooten/mailchimp-for-wordpress#85]
Was this a mistake?

https://github.com/dannyvankooten/mailchimp-for-wordpress/blob/master/includes/class-form-manager.php#L335

**Comment by dannyvankooten** [comment]
Hi @fuzaylov ,

No, the field is a "honeypot field" which later gets hidden through CSS and JavaScript.

https://github.com/dannyvankooten/mailchimp-for-wordpress/blob/master/includes/class-form-manager.php#L372 (CSS)
https://github.com/dannyvankooten/mailchimp-for-wordpress/blob/master/includes/class-form-manager.php#L404 (JS)

Is it still visible on your site?

**Comment by fuzaylov** [comment]
Yes, I can see it. Am I missing a config?

**Comment by dannyvankooten** [comment]
That's weird @fuzaylov, are you on the master branch or at least version 2.2.7? Do you have a link to your site so I can see this happening?

**Comment by fuzaylov** [comment]
Yes, it's all new. I can't share the website yet unfortunately, but I guess the issue is because we use a custom template. Anyway, we can hide it with css, but just wanted to make sure this wasn't a mistake on your part. :)

Thank you!
