### ISSUE TITLE
mailchimp.php contains a typographical/coding error

### ISSUE THREAD

**Issue by EverydaySpeeches** [dannyvankooten/mailchimp-for-wordpress#86]
Running Version: 1.4.2

in the function mailchimpSF_load_resources()
and in the conditional if (get_option('mc_use_datepicker') == 'on' && !is_admin())

you need to remove the preceding '/' from both '/css/flick/flick.css' and '/js/datepicker.js' so that it reads
if (get_option('mc_use_datepicker') == 'on' && !is_admin()) {
		// Datepicker theme
		wp_enqueue_style('flick', MCSF_URL.'css/flick/flick.css');
		// Datepicker JS
		wp_enqueue_script('datepicker', MCSF_URL.'js/datepicker.js', array('jquery','jquery-ui-core'));
	}

The consequence is that (using my site as the example) the respective addresses to the files become:
http://www.everydayspeeches.com/wp-content/plugins/mailchimp//css/flick/flick.css
http://www.everydayspeeches.com/wp-content/plugins/mailchimp//js/datepicker.js

which should be:
http://www.everydayspeeches.com/wp-content/plugins/mailchimp/css/flick/flick.css
http://www.everydayspeeches.com/wp-content/plugins/mailchimp/js/datepicker.js

Regards,

Travis

**Comment by dannyvankooten** [comment]
Hi @EverydaySpeeches,

Thank you for the detailed report but the code snippet you're referring to does not appear in the MailChimp for WordPress plugin, I believe you'r referring to another plugin..
