### ISSUE TITLE
Two Identical Checkboxes

### ISSUE THREAD

**Issue by MyPeacefulOasis** [dannyvankooten/mailchimp-for-wordpress#87]
When I choose the option to add the checkbox to the comment form, under checkbox settings, I get two checkboxes showing up in my blog comment area saying the same thing... to be added to mailing list.

How do I get rid of one of them?
Thanks,
Janette
example at:http://mypeacefuloasis.com/boost-mood-blog/boost-mood-post-5/

**Comment by dannyvankooten** [comment]
Hi @MyPeacefulOasis,

That is strange but most likely your theme is calling the action hook ( the one the plugin uses to show the checkbox) twice.

I would suggest contacting your theme author and asking him to look into his comment form template. The following snippet of code should only appear once.

```php
do_action( 'comment_form' )
```

**Comment by MyPeacefulOasis** [comment]
okay thanks.
