### ISSUE TITLE
HTTP Error: There are no HTTP transports available which can complete the requested request.

### ISSUE THREAD

**Issue by shersinghrajput** [dannyvankooten/mailchimp-for-wordpress#90]
hi my self shersingh rajput and i ma using the mailchip plugin in localhost it's working but i am host in site for a server http://2point0music.com so it's not working it's given to a error (HTTP Error: There are no HTTP transports available which can complete the requested request. ) this plz given to me a solution for this  problem

**Comment by dannyvankooten** [comment]
Hi @shersinghrajput ,

This means your server is incorrectly configured and does not have PHP CURL installed. Please contact your webhost and ask him to install PHP CURL.

That should fix the issue. :) Hope that helps!

**Comment by shersinghrajput** [comment]
thank's to help me
