### ISSUE TITLE
Form Settings: Send an email copy of the form data doesn't work

### ISSUE THREAD

**Issue by taastephens** [dannyvankooten/mailchimp-for-wordpress#94]
I have not received an email for every test sign up that I have done. According to the attached, I should be able to with Double Opt in disabled. 

Please help.

![forum](https://cloud.githubusercontent.com/assets/12161498/7382721/6ebdf052-edd0-11e4-9205-c22618de7c70.png)

**Comment by dannyvankooten** [comment]
Hi @taastephens , did you enable this setting in the form settings?

![image](https://cloud.githubusercontent.com/assets/885856/7386411/f20ae2a2-ee53-11e4-8833-64573c18e263.png)

**Comment by taastephens** [comment]
Yes.

Okay so funny story, once we took it off of our development site it works. So looks like the issue can be closed now.

Thanks for your help, sorry for the inconvenience.

Tiffany Stephens - Marketing Product Specialist
Intelligent Software Solutions
p. 719.452.7622| f. 719.452.7001 | main: 719.452.7000
www.issinc.com <http://www.issinc.com/> | LinkedIn: intelligent-software-solutions

**Comment by dannyvankooten** [comment]
Thanks for confirming @taastephens - most likely, your development site does not have PHP `mail()` correctly configured. The plugin uses the default WordPress email functionality so chances are other WP emails aren't working there either. :)
