### ISSUE TITLE
Honeypot scripting issue in IE

### ISSUE THREAD

**Issue by renaissancejames** [dannyvankooten/mailchimp-for-wordpress#96]
Hi,

Since updating the plugin recently, a client has been reporting that the are getting scripting issue on the site, upon further investigation it links to the line

honeypot.setAttribute('type','hidden');

I would guess this issue exists to do with differences between js and jquery 
http://jsperf.com/jquery-attr-vs-native-setattribute

And as such should be using the .attr instead of .setAttribute, I believe.

Can you advise the location of this line and I can test it out, I have searched and been unable to find it, but am pretty sure its linked directly to this plugin.

**Comment by dannyvankooten** [comment]
Great catch @renaissancejames - will be fixed in the next release!
