### ISSUE TITLE
IE Compatibility with V2.3

### ISSUE THREAD

**Issue by leejmurphy** [dannyvankooten/mailchimp-for-wordpress#97]
I have updated to version 2.3, i'm specifically having an issue with IE8 compatibility so I was pleased to see a fix in this version. However the replacement code, specifically this line, gives me the script error message **Could not get the type property. This command is not supported.** (Currently running self hosted WP v4.2.1)
```
honeypot.type = ‘hidden’; 
```
Please do let me know if I can provide you with any further information. Thanks

**Comment by dannyvankooten** [comment]
Hi @leejmurphy - is this happening in IE8 specifically or in versions before IE8?

**Comment by dannyvankooten** [comment]
This should be fixed in version 2.3.1, which we've just pushed to w.org as well!

https://github.com/dannyvankooten/mailchimp-for-wordpress/releases/tag/2.3.1

**Comment by leejmurphy** [comment]
Hi @dannyvankooten - apologies i may have been misleading when I said specifically. I am getting the issue in IE8, it looks like it doesn't working in versions IE6-IE7 either (personally only worried about IE8 though). I will upgrade to 2.3.1 and check if it is working.

**Comment by leejmurphy** [comment]
@dannyvankooten v2.3.1 seems to fix that specific issue. However further down I now receive this error **Object doesn't support this property or method** for the line 
```
b.attachEvent( 'onclick', addSubmittedClass.bind(f));
```
Thanks for your prompt reply.

**Comment by dannyvankooten** [comment]
Thanks @leejmurphy - that error shouldn't cause any major issues but is definitely something we're going to fix.

(It's a helper that attaches a "submitted" CSS class to your form once it is submitted, so you can do something with the styling).

 I'll reopen this issue and will keep you updated - I don't have IE8 lying around at this moment so it's a little hard to test right now.
