### ISSUE TITLE
CSS font color problem, input field behavior

### ISSUE THREAD

**Issue by rashunda** [dannyvankooten/mailchimp-for-wordpress#98]
For the life of me I can't change the input field font color. I could change the style to italics, but not the color. Here's the code I used when I edited the CSS:

```
.mc4wp-form input {
	font-style: italic;
	color: #3a3a3a;
}
/* input fields */
```
Input field behavior: I would like for the text "type email + enter" to disappear when the site visitor clicks inside the field. As of now, the user has to actually start typing for the text to disappear. If someone clicks, and the filler text doesn't disappear, they may think the sign-up field doesn't work. Is there a way to adjust this?

My site is rashunda.com

Kind regards,
R

**Comment by hchouhan** [comment]
@rashunda,
I tested your website and the color CSS styling does work. The color is applied to the text which the end user types into the field. 
The color for "type email + enter" is controlled by the browser. To style it you would need to style the placeholder element. 
````
.mc4wp-form input::-webkit-input-placeholder,
.mc4wp-form input:-moz-placeholder,
.mc4wp-form input::-moz-placeholder,
.mc4wp-form input:-ms-input-placeholder
 {
   color: #3a3a3a;
}
````

You can read more about it here https://css-tricks.com/snippets/css/style-placeholder-text/.

About your last query, currently the way things are is default browser behavior. If you wish to hide the text when someone clicks on the input field, you would need to add additional JavaScript to your theme. And I'm afraid I would not be able to assist you with it as it's outside the scope of support.

**Comment by rashunda** [comment]
Thanks for this. I'll try to find other help for the javascript.
